export const countries = [
	{ code: "AD", label: "Andorra", phone: "376" , persian: "آندورا" },
	{
		code: "AE",
		label: "United Arab Emirates",
		phone: "971",
		persian: "امارات متحده عربی		" },
	{ code: "AF", label: "Afghanistan", phone: "93" , persian: "افغانستان" },
	{
		code: "AG",
		label: "Antigua and Barbuda",
		phone: "1-268",
		persian: "آنتیگوا و باربودا" },
	{ code: "AI", label: "Anguilla", phone: "1-264" , persian: "آنگویلا" },
	{ code: "AL", label: "Albania", phone: "355" , persian: "آلبانی" },
	{ code: "AM", label: "Armenia", phone: "374" , persian: "ارمنستان" },
	{ code: "AO", label: "Angola", phone: "244" , persian: "آنگولا" },
	{ code: "AQ", label: "Antarctica", phone: "672" , persian: "جنوبگان" },
	{ code: "AR", label: "Argentina", phone: "54" , persian: "آرژانتین" },
	{ code: "AS", label: "American Samoa", phone: "1-684" , persian: "ساموآ" },
	{ code: "AT", label: "Austria", phone: "43" , persian: "اتریش" },
	{
		code: "AU",
		label: "Australia",
		phone: "61",
		suggested: true,
		persian: "استرالیا" },
	{ code: "AW", label: "Aruba", phone: "297" , persian: "آروبا" },
	{ code: "AX", label: "Alland Islands", phone: "358" , persian: "جزایر الند" },
	{ code: "AZ", label: "Azerbaijan", phone: "994" , persian: "آذربایجان" },
	{
		code: "BA",
		label: "Bosnia and Herzegovina",
		phone: "387",
		persian: "بوسنی – هرزگوین" },
	{ code: "BB", label: "Barbados", phone: "1-246" , persian: "باربادوس" },
	{ code: "BD", label: "Bangladesh", phone: "880" , persian: "بنگلادش" },
	{ code: "BE", label: "Belgium", phone: "32" , persian: "بلژیک" },
	{ code: "BF", label: "Burkina Faso", phone: "226" , persian: "بورکینا فاسو	" },
	{ code: "BG", label: "Bulgaria", phone: "359" , persian: "بلغارستان" },
	{ code: "BH", label: "Bahrain", phone: "973" , persian: "بحرین" },
	{ code: "BI", label: "Burundi", phone: "257" , persian: "بوروندی" },
	{ code: "BJ", label: "Benin", phone: "229" , persian: "بنین" },
	{ code: "BL", label: "Saint Barthelemy", phone: "590" , persian: "سنت بارتلمی" },
	{ code: "BM", label: "Bermuda", phone: "1-441" , persian: "برمودا" },
	{ code: "BN", label: "Brunei Darussalam", phone: "673" , persian: "بروئنی" },
	{ code: "BO", label: "Bolivia", phone: "591" , persian: "بولیوی" },
	{ code: "BR", label: "Brazil", phone: "55" , persian: "برزیل" },
	{ code: "BS", label: "Bahamas", phone: "1-242" , persian: "باهاما" },
	{ code: "BT", label: "Bhutan", phone: "975" , persian: "بوتان" },
	{ code: "BV", label: "Bouvet Island", phone: "47" , persian: "جزیره بووه" },
	{ code: "BW", label: "Botswana", phone: "267" , persian: "بوتساوانا" },
	{ code: "BY", label: "Belarus", phone: "375" , persian: "بلاروس (روسیه سفید)" },
	{ code: "BZ", label: "Belize", phone: "501" , persian: "بلیز" },
	{
		code: "CA",
		label: "Canada",
		phone: "1",
		suggested: true,
		persian: "کانادا" },
	{
		code: "CC",
		label: "Cocos (Keeling) Islands",
		phone: "61",
		persian: "جزایر کوکوس (کیلینگ)." },
	{
		code: "CD",
		label: "Congo, Democratic Republic of the",
		phone: "243",
		persian: "کنگو" },
	{
		code: "CF",
		label: "Central African Republic",
		phone: "236",
		persian: "جمهوری آفریقای مرکزی" },
	{
		code: "CG",
		label: "Congo, Republic of the",
		phone: "242",
		persian: "کنگو" },
	{ code: "CH", label: "Switzerland", phone: "41" , persian: "سوئیس	" },
	{ code: "CI", label: "Cote d'Ivoire", phone: "225" , persian: "ساحل عاج" },
	{ code: "CK", label: "Cook Islands", phone: "682" , persian: "جزایر کوک" },
	{ code: "CL", label: "Chile", phone: "56" , persian: "شیلی" },
	{ code: "CM", label: "Cameroon", phone: "237" , persian: "کامرون" },
	{ code: "CN", label: "China", phone: "86" , persian: "چین" },
	{ code: "CO", label: "Colombia", phone: "57" , persian: "کلمبیا	" },
	{ code: "CR", label: "Costa Rica", phone: "506" , persian: "کاستاریکا" },
	{ code: "CU", label: "Cuba", phone: "53" , persian: "کوبا" },
	{ code: "CV", label: "Cape Verde", phone: "238" , persian: "کیپ ورد	" },
	{ code: "CW", label: "Curacao", phone: "599" , persian: "کوراسائو" },
	{ code: "CX", label: "Christmas Island", phone: "61" , persian: "جزیره کریسمس" },
	{ code: "CY", label: "Cyprus", phone: "357" , persian: "قبرس" },
	{ code: "CZ", label: "Czech Republic", phone: "420" , persian: "جمهوری چک	" },
	{
		code: "DE",
		label: "Germany",
		phone: "49",
		suggested: true,
		persian: "آلمان" },
	{ code: "DJ", label: "Djibouti", phone: "253" , persian: "جیبوتی" },
	{ code: "DK", label: "Denmark", phone: "45" , persian: "دانمارک" },
	{ code: "DM", label: "Dominica", phone: "1-767" , persian: "دومینیکا" },
	{
		code: "DO",
		label: "Dominican Republic",
		phone: "1-809",
		persian: "جمهوری دومینیک		" },
	{ code: "DZ", label: "Algeria", phone: "213" , persian: "الجزیره" },
	{ code: "EC", label: "Ecuador", phone: "593" , persian: "اکوادور" },
	{ code: "EE", label: "Estonia", phone: "372" , persian: "استونی" },
	{ code: "EG", label: "Egypt", phone: "20" , persian: "مصر" },
	{ code: "EH", label: "Western Sahara", phone: "212" , persian: "صحرای غربی" },
	{ code: "ER", label: "Eritrea", phone: "291" , persian: "اریتره" },
	{ code: "ES", label: "Spain", phone: "34" , persian: "اسپانیا" },
	{ code: "ET", label: "Ethiopia", phone: "251" , persian: "اتیوپی" },
	{ code: "FI", label: "Finland", phone: "358" , persian: "فنلاند" },
	{ code: "FJ", label: "Fiji", phone: "679" , persian: "فیجی" },
	{
		code: "FK",
		label: "Falkland Islands (Malvinas)",
		phone: "500",
		persian: "جزایر فالکلند (مالویناس)" },
	{
		code: "FM",
		label: "Micronesia, Federated States of",
		phone: "691",
		persian: "میکرونزی، ایالات فدرال" },
	{ code: "FO", label: "Faroe Islands", phone: "298" , persian: "جزایر فارو" },
	{
		code: "FR",
		label: "France",
		phone: "33",
		suggested: true,
		persian: "فرانسه" },
	{ code: "GA", label: "Gabon", phone: "241" , persian: "گابن" },
	{ code: "GB", label: "United Kingdom", phone: "44" , persian: "انگلستان" },
	{ code: "GD", label: "Grenada", phone: "1-473" , persian: "گرانادا	" },
	{ code: "GE", label: "Georgia", phone: "995" , persian: "گرجستان" },
	{ code: "GF", label: "French Guiana", phone: "594" , persian: "گویان فرانسه" },
	{ code: "GG", label: "Guernsey", phone: "44" , persian: "گرنزی" },
	{ code: "GH", label: "Ghana", phone: "233" , persian: "غنا" },
	{ code: "GI", label: "Gibraltar", phone: "350" , persian: "جبل الطارق" },
	{ code: "GL", label: "Greenland", phone: "299" , persian: "گرینلند" },
	{ code: "GM", label: "Gambia", phone: "220" , persian: "گامبیا" },
	{ code: "GN", label: "Guinea", phone: "224" , persian: "گینه" },
	{ code: "GP", label: "Guadeloupe", phone: "590" , persian: "گوادلوپ" },
	{ code: "GQ", label: "Equatorial Guinea", phone: "240" , persian: "گینه استوایی" },
	{ code: "GR", label: "Greece", phone: "30" , persian: "یونان" },
	{
		code: "GS",
		label: "South Georgia and the South Sandwich Islands",
		phone: "500",
		persian: "جورجیا جنوبی و جزایر ساندویچ جنوبی" },
	{ code: "GT", label: "Guatemala", phone: "502" , persian: "گواتمالا" },
	{ code: "GU", label: "Guam", phone: "1-671" , persian: "گوام" },
	{ code: "GW", label: "Guinea-Bissau", phone: "245" , persian: "گینه بیسائو" },
	{ code: "GY", label: "Guyana", phone: "592" , persian: "گویان" },
	{ code: "HK", label: "Hong Kong", phone: "852" , persian: "هنگ کنگ" },
	{
		code: "HM",
		label: "Heard Island and McDonald Islands",
		phone: "672",
		persian: "جزیره هرد و جزایر مک دونالد" },
	{ code: "HN", label: "Honduras", phone: "504" , persian: "هندوراس" },
	{ code: "HR", label: "Croatia", phone: "385" , persian: "کرواسی" },
	{ code: "HT", label: "Haiti", phone: "509" , persian: "هائیتی" },
	{ code: "HU", label: "Hungary", phone: "36" , persian: "مجارستان" },
	{ code: "ID", label: "Indonesia", phone: "62" , persian: "اندونزی" },
	{ code: "IE", label: "Ireland", phone: "353" , persian: "ایرلند" },
	{ code: "IL", label: "Israel", phone: "972" , persian: "اسرائيل" },
	{ code: "IM", label: "Isle of Man", phone: "44" , persian: "جزیره من" },
	{ code: "IN", label: "India", phone: "91" , persian: "هند" },
	{
		code: "IO",
		label: "British Indian Ocean Territory",
		phone: "246",
		persian: "بریتانیا" },
	{ code: "IQ", label: "Iraq", phone: "964" , persian: "عراق" },
	{
		code: "IR",
		label: "Iran, Islamic Republic of",
		phone: "98",
		persian: "ایران" },
	{ code: "IS", label: "Iceland", phone: "354" , persian: "ایسلند" },
	{ code: "IT", label: "Italy", phone: "39" , persian: "ایتالیا" },
	{ code: "JE", label: "Jersey", phone: "44" , persian: "جرسی" },
	{ code: "JM", label: "Jamaica", phone: "1-876" , persian: "جامائیکا" },
	{ code: "JO", label: "Jordan", phone: "962" , persian: "اردن" },
	{
		code: "JP",
		label: "Japan",
		phone: "81",
		suggested: true,
		persian: "ژاپن" },
	{ code: "KE", label: "Kenya", phone: "254" , persian: "کنیا" },
	{ code: "KG", label: "Kyrgyzstan", phone: "996" , persian: "قرقیزستان" },
	{ code: "KH", label: "Cambodia", phone: "855" , persian: "کامبوج" },
	{ code: "KI", label: "Kiribati", phone: "686" , persian: "کیریباتی" },
	{ code: "KM", label: "Comoros", phone: "269" , persian: "کومور" },
	{
		code: "KN",
		label: "Saint Kitts and Nevis",
		phone: "1-869",
		persian: "سنت کیتس و نویس" },
	{
		code: "KP",
		label: "Korea, Democratic People's Republic of",
		phone: "850",
		persian: "شمالی" },
	{ code: "KR", label: "Korea, Republic of", phone: "82" , persian: "کره جنوبی 	" },
	{ code: "KW", label: "Kuwait", phone: "965" , persian: "کویت" },
	{ code: "KY", label: "Cayman Islands", phone: "1-345" , persian: "جزایر کیمن" },
	{ code: "KZ", label: "Kazakhstan", phone: "7" , persian: "قزاقستان" },
	{
		code: "LA",
		label: "Lao People's Democratic Republic",
		phone: "856",
		persian: "جمهوری دموکراتیک خلق لائوس" },
	{ code: "LB", label: "Lebanon", phone: "961" , persian: "لبنان" },
	{ code: "LC", label: "Saint Lucia", phone: "1-758" , persian: "سنت لوسیا" },
	{ code: "LI", label: "Liechtenstein", phone: "423" , persian: "لیختن‌اشتاین" },
	{ code: "LK", label: "Sri Lanka", phone: "94" , persian: "سریلانکا	" },
	{ code: "LR", label: "Liberia", phone: "231" , persian: "لیبریا" },
	{ code: "LS", label: "Lesotho", phone: "266" , persian: "لسوتو" },
	{ code: "LT", label: "Lithuania", phone: "370" , persian: "لیتوانی" },
	{ code: "LU", label: "Luxembourg", phone: "352" , persian: "لوکزامبورگ" },
	{ code: "LV", label: "Latvia", phone: "371" , persian: "لتونی" },
	{ code: "LY", label: "Libya", phone: "218" , persian: "لیبی" },
	{ code: "MA", label: "Morocco", phone: "212" , persian: "مراکش" },
	{ code: "MC", label: "Monaco", phone: "377" , persian: "موناکو" },
	{
		code: "MD",
		label: "Moldova, Republic of",
		phone: "373",
		persian: "مولداوری" },
	{ code: "ME", label: "Montenegro", phone: "382" , persian: "مونتنگرو" },
	{
		code: "MF",
		label: "Saint Martin (French part)",
		phone: "590",
		persian: "سنت مارتین (بخش فرانسوی)" },
	{ code: "MG", label: "Madagascar", phone: "261" , persian: "ماداگاسکار" },
	{ code: "MH", label: "Marshall Islands", phone: "692" , persian: "جزایر مارشال" },
	{
		code: "MK",
		label: "Macedonia, the Former Yugoslav Republic of",
		phone: "389",
		persian: "مقدونیه		" },
	{ code: "ML", label: "Mali", phone: "223" , persian: "مالی" },
	{ code: "MM", label: "Myanmar", phone: "95" , persian: "میانمار" },
	{ code: "MN", label: "Mongolia", phone: "976" , persian: "مغولستان" },
	{ code: "MO", label: "Macao", phone: "853" , persian: "ماکائو" },
	{
		code: "MP",
		label: "Northern Mariana Islands",
		phone: "1-670",
		persian: "جزایر ماریانای شمالی" },
	{ code: "MQ", label: "Martinique", phone: "596" , persian: "مارتینیک" },
	{ code: "MR", label: "Mauritania", phone: "222" , persian: "موریتانی	" },
	{ code: "MS", label: "Montserrat", phone: "1-664" , persian: "مونتسرات" },
	{ code: "MT", label: "Malta", phone: "356" , persian: "مالتا" },
	{ code: "MU", label: "Mauritius", phone: "230" , persian: "موریس" },
	{ code: "MV", label: "Maldives", phone: "960" , persian: "مالدیو" },
	{ code: "MW", label: "Malawi", phone: "265" , persian: "مالاوی" },
	{ code: "MX", label: "Mexico", phone: "52" , persian: "مکزیک" },
	{ code: "MY", label: "Malaysia", phone: "60" , persian: "مالزی" },
	{ code: "MZ", label: "Mozambique", phone: "258" , persian: "موزامبیک" },
	{ code: "NA", label: "Namibia", phone: "264" , persian: "نامبیا" },
	{ code: "NC", label: "New Caledonia", phone: "687" , persian: "کالدونیای جدید" },
	{ code: "NE", label: "Niger", phone: "227" , persian: "نیجر" },
	{ code: "NF", label: "Norfolk Island", phone: "672" , persian: "جزیره نورفولک" },
	{ code: "NG", label: "Nigeria", phone: "234" , persian: "نیجریه" },
	{ code: "NI", label: "Nicaragua", phone: "505" , persian: "نیکاراگوئه" },
	{ code: "NL", label: "Netherlands", phone: "31" , persian: "هلند" },
	{ code: "NO", label: "Norway", phone: "47" , persian: "نروژ" },
	{ code: "NP", label: "Nepal", phone: "977" , persian: "نپال" },
	{ code: "NR", label: "Nauru", phone: "674" , persian: "نائورو" },
	{ code: "NU", label: "Niue", phone: "683" , persian: "نیوئه" },
	{ code: "NZ", label: "New Zealand", phone: "64" , persian: "نیوزیلند	" },
	{ code: "OM", label: "Oman", phone: "968" , persian: "عمان" },
	{ code: "PA", label: "Panama", phone: "507" , persian: "پاناما" },
	{ code: "PE", label: "Peru", phone: "51" , persian: "پرو" },
	{ code: "PF", label: "French Polynesia", phone: "689" , persian: "پلینزی فرانسه" },
	{ code: "PG", label: "Papua New Guinea", phone: "675" , persian: "پاپوا گینه نو	" },
	{ code: "PH", label: "Philippines", phone: "63" , persian: "فیلیپین" },
	{ code: "PK", label: "Pakistan", phone: "92" , persian: "پاکستان" },
	{ code: "PL", label: "Poland", phone: "48" , persian: "لهستان" },
	{
		code: "PM",
		label: "Saint Pierre and Miquelon",
		phone: "508",
		persian: "سنت پیر و میکلون" },
	{ code: "PN", label: "Pitcairn", phone: "870" , persian: "پیتکرن" },
	{ code: "PR", label: "Puerto Rico", phone: "1" , persian: "پورتوریکو" },
	{
		code: "PS",
		label: "Palestine, State of",
		phone: "970",
		persian: "فلسطین، ایالت" },
	{ code: "PT", label: "Portugal", phone: "351" , persian: "پرتغال" },
	{ code: "PW", label: "Palau", phone: "680" , persian: "پالائو" },
	{ code: "PY", label: "Paraguay", phone: "595" , persian: "پاراگوئه" },
	{ code: "QA", label: "Qatar", phone: "974" , persian: "قطر" },
	{ code: "RE", label: "Reunion", phone: "262" , persian: "ریونین" },
	{ code: "RO", label: "Romania", phone: "40" , persian: "رومانی" },
	{ code: "RS", label: "Serbia", phone: "381" , persian: "صربستان" },
	{ code: "RU", label: "Russian Federation", phone: "7" , persian: "روسیه" },
	{ code: "RW", label: "Rwanda", phone: "250" , persian: "روآندا" },
	{ code: "SA", label: "Saudi Arabia", phone: "966" , persian: "عربستان سعودی	" },
	{ code: "SB", label: "Solomon Islands", phone: "677" , persian: "جزایر سلیمان	" },
	{ code: "SC", label: "Seychelles", phone: "248" , persian: "جمهوری سیشل	" },
	{ code: "SD", label: "Sudan", phone: "249" , persian: "سودان" },
	{ code: "SE", label: "Sweden", phone: "46" , persian: "سوئد" },
	{ code: "SG", label: "Singapore", phone: "65" , persian: "سنگاپور" },
	{ code: "SH", label: "Saint Helena", phone: "290" , persian: "سنت هلنا" },
	{ code: "SI", label: "Slovenia", phone: "386" , persian: "اسلونی" },
	{
		code: "SJ",
		label: "Svalbard and Jan Mayen",
		phone: "47",
 persian: "سوالبارد و یان ماین" },
	{ code: "SK", label: "Slovakia", phone: "421" , persian: "اسلواکی	" },
	{ code: "SL", label: "Sierra Leone", phone: "232" , persian: "سیرا لئون	" },
	{ code: "SM", label: "San Marino", phone: "378" , persian: "سن مارینو" },
	{ code: "SN", label: "Senegal", phone: "221" , persian: "سنگال" },
	{ code: "SO", label: "Somalia", phone: "252" , persian: "سومالی	" },
	{ code: "SR", label: "Suriname", phone: "597" , persian: "سورینام" },
	{ code: "SS", label: "South Sudan", phone: "211" , persian: "سودان جنوبی" },
	{
		code: "ST",
		label: "Sao Tome and Principe",
		phone: "239",
 persian: "سائوتومه و پرنسیپ" },
	{ code: "SV", label: "El Salvador", phone: "503" , persian: "السالوادور	" },
	{
		code: "SX",
		label: "Sint Maarten (Dutch part)",
		phone: "1-721",
 persian: "سینت مارتن (بخش هلندی)" },
	{
		code: "SY",
		label: "Syrian Arab Republic",
		phone: "963",
 persian: "سوریه" },
	{ code: "SZ", label: "Swaziland", phone: "268" , persian: "سوارزیلند	" },
	{
		code: "TC",
		label: "Turks and Caicos Islands",
		phone: "1-649",
 persian: "جزایر تورکس و کایکوس" },
	{ code: "TD", label: "Chad", phone: "235" , persian: "چاد" },
	{
		code: "TF",
		label: "French Southern Territories",
		phone: "262",
 persian: "سرزمین های جنوبی فرانسه" },
	{ code: "TG", label: "Togo", phone: "228" , persian: "توگو	" },
	{ code: "TH", label: "Thailand", phone: "66" , persian: "تایلند" },
	{ code: "TJ", label: "Tajikistan", phone: "992" , persian: "تاجیکستان	" },
	{ code: "TK", label: "Tokelau", phone: "690" , persian: "توکلائو" },
	{ code: "TL", label: "Timor-Leste", phone: "670" , persian: "تیمور شرقی" },
	{ code: "TM", label: "Turkmenistan", phone: "993" , persian: "ترکمنستان	" },
	{ code: "TN", label: "Tunisia", phone: "216" , persian: "تونس" },
	{ code: "TO", label: "Tonga", phone: "676" , persian: "تونگا" },
	{ code: "TR", label: "Turkey", phone: "90" , persian: "ترکیه" },
	{
		code: "TT",
		label: "Trinidad and Tobago",
		phone: "1-868",
 persian: "ترینیداد و توباگو " },
	{ code: "TV", label: "Tuvalu", phone: "688" , persian: "توالا" },
	{
		code: "TW",
		label: "Taiwan, Province of China",
		phone: "886",
 persian: "تایوان" },
	{
		code: "TZ",
		label: "United Republic of Tanzania",
		phone: "255",
 persian: "تانزانیا" },
	{ code: "UA", label: "Ukraine", phone: "380" , persian: "اوکراین" },
	{ code: "UG", label: "Uganda", phone: "256" , persian: "اوگاندا" },
	{
		code: "US",
		label: "United States",
		phone: "1",
		suggested: true,
 persian: "ایالات متحده آمریکا " },
	{ code: "UY", label: "Uruguay", phone: "598" , persian: "اوروگوئه	" },
	{ code: "UZ", label: "Uzbekistan", phone: "998" , persian: "ازبکستان	" },
	{
		code: "VA",
		label: "Holy See (Vatican City State)",
		phone: "379",
 persian: "واتیکان " },
	{
		code: "VC",
		label: "Saint Vincent and the Grenadines",
		phone: "1-784",
 persian: "سنت وینسنت و گرنادین ها" },
	{ code: "VE", label: "Venezuela", phone: "58" , persian: "ونزوئلا" },
	{
		code: "VG",
		label: "British Virgin Islands",
		phone: "1-284",
 persian: "جزایر ویرجین بریتانیا" },
	{
		code: "VI",
		label: "US Virgin Islands",
		phone: "1-340",
 persian: "جزایر ویرجین ایالات متحده" },
	{ code: "VN", label: "Vietnam", phone: "84" , persian: "ویتنام" },
	{ code: "VU", label: "Vanuatu", phone: "678" , persian: "وانوآتو" },
	{ code: "WF", label: "Wallis and Futuna", phone: "681" , persian: "والیس و فوتونا" },
	{ code: "WS", label: "Samoa", phone: "685" , persian: "ساموآ" },
	{ code: "XK", label: "Kosovo", phone: "383" , persian: "کوزوو" },
	{ code: "YE", label: "Yemen", phone: "967" , persian: "یمن" },
	{ code: "YT", label: "Mayotte", phone: "262" , persian: "مایوت" },
	{ code: "ZA", label: "South Africa", phone: "27" , persian: "South Africa" },
	{ code: "ZM", label: "Zambia", phone: "260" , persian: "زامبیا" },
	{ code: "ZW", label: "Zimbabwe", phone: "263" , persian: "زیمباوه" },
];
